/**
 * Curated list of family-friendly movie titles from IMDB
 * Ratings: G, PG, PG-13
 *
 * This list contains popular and recognizable movie titles suitable for game names.
 */

const FAMILY_FRIENDLY_MOVIES = [
  // G Rated
  "Toy Story",
  "Finding Nemo",
  "The Lion King",
  "Up",
  "Wall-E",
  "Inside Out",
  "Coco",
  "Ratatouille",
  "Monsters Inc",
  "Finding Dory",
  "The Incredibles",
  "Cars",
  "Brave",
  "Moana",
  "Frozen",
  "Zootopia",
  "Big Hero 6",
  "Tangled",
  "Wreck-It Ralph",
  "The Good Dinosaur",
  "Soul",
  "Luca",
  "Turning Red",
  "Encanto",
  "The Little Mermaid",
  "Beauty and the Beast",
  "Aladdin",
  "Cinderella",
  "Mulan",
  "Pocahontas",
  "The Jungle Book",
  "Bambi",
  "Dumbo",
  "Lady and the Tramp",
  "101 Dalmatians",
  "The Aristocats",
  "Robin Hood",
  "The Fox and the Hound",
  "Oliver and Company",
  "The Emperor's New Groove",
  "Lilo and Stitch",
  "Brother Bear",
  "Bolt",
  "Winnie the Pooh",
  "Paddington",
  "Paddington 2",
  "Sing",
  "The Secret Life of Pets",
  "Despicable Me",
  "Minions",
  "The Lorax",
  "Horton Hears a Who",
  "Ice Age",
  "Rio",
  "Madagascar",
  "Kung Fu Panda",
  "How to Train Your Dragon",
  "Shrek",
  "Puss in Boots",
  "Megamind",
  "The Croods",
  "Turbo",
  "Home",
  "Trolls",
  "The Boss Baby",
  "Abominable",
  "The Bad Guys",

  // PG Rated
  "E.T. the Extra-Terrestrial",
  "The Goonies",
  "Back to the Future",
  "Jumanji",
  "Mrs. Doubtfire",
  "Home Alone",
  "Home Alone 2",
  "Matilda",
  "The Sandlot",
  "Honey I Shrunk the Kids",
  "The Parent Trap",
  "Jurassic Park",
  "Night at the Museum",
  "Elf",
  "The Polar Express",
  "Willy Wonka",
  "Charlie and the Chocolate Factory",
  "Fantastic Mr. Fox",
  "The Princess Bride",
  "Hook",
  "The NeverEnding Story",
  "Labyrinth",
  "The Dark Crystal",
  "The Muppet Movie",
  "Mary Poppins",
  "Chitty Chitty Bang Bang",
  "Swiss Family Robinson",
  "The Wizard of Oz",
  "The Sound of Music",
  "My Neighbor Totoro",
  "Spirited Away",
  "Howl's Moving Castle",
  "Ponyo",
  "Kiki's Delivery Service",
  "Castle in the Sky",
  "The Cat Returns",
  "Arrietty",
  "The Wind Rises",
  "From Up on Poppy Hill",
  "Earwig and the Witch",
  "Harry Potter and the Sorcerer's Stone",
  "Harry Potter and the Chamber of Secrets",
  "The Chronicles of Narnia",
  "Percy Jackson",
  "Stardust",
  "The Spiderwick Chronicles",
  "Bridge to Terabithia",
  "Where the Wild Things Are",
  "Hugo",
  "The BFG",
  "A Wrinkle in Time",
  "Dolittle",
  "The Call of the Wild",
  "Peter Rabbit",
  "Christopher Robin",
  "Dumbo",
  "The Secret Garden",
  "The Witches",
  "Space Jam",
  "Looney Tunes Back in Action",
  "Tom and Jerry",
  "The Smurfs",
  "Alvin and the Chipmunks",
  "Stuart Little",
  "Babe",
  "Beethoven",
  "Air Bud",
  "Racing Stripes",
  "Free Willy",
  "Flipper",
  "Fly Away Home",
  "The Black Stallion",
  "National Velvet",

  // PG-13 Rated
  "The Avengers",
  "Guardians of the Galaxy",
  "Black Panther",
  "Spider-Man: Into the Spider-Verse",
  "The Amazing Spider-Man",
  "Spider-Man: Homecoming",
  "Ant-Man",
  "Doctor Strange",
  "Thor",
  "Captain America",
  "Iron Man",
  "Shazam",
  "Wonder Woman",
  "Aquaman",
  "Big",
  "Freaky Friday",
  "13 Going on 30",
  "The Karate Kid",
  "The Mighty Ducks",
  "Cool Runnings",
  "Remember the Titans",
  "The Blind Side",
  "Field of Dreams",
  "A League of Their Own",
  "Miracle",
  "Rudy",
  "The Rookie",
  "Moneyball",
  "Secretariat",
  "Seabiscuit",
  "National Treasure",
  "Indiana Jones and the Last Crusade",
  "The Mummy",
  "Journey to the Center of the Earth",
  "The Time Machine",
  "Tomorrowland",
  "A.I. Artificial Intelligence",
  "Real Steel",
  "WALL-E",
  "I Robot",
  "Transformers",
  "Pacific Rim",
  "The Maze Runner",
  "Divergent",
  "The Hunger Games",
  "Ender's Game",
  "Ready Player One",
  "Tron: Legacy",
  "Interstellar",
  "The Martian",
  "Gravity",
  "Apollo 13",
  "Hidden Figures",
  "October Sky",
  "The Imitation Game",
  "Catch Me If You Can",
  "The Terminal",
  "Forrest Gump",
  "The Greatest Showman",
  "La La Land",
  "Pitch Perfect",
  "School of Rock",
  "Hairspray",
  "Footloose",
  "Mamma Mia",
  "Enchanted",
  "Into the Woods",
  "The Princess Diaries",
  "Ella Enchanted",
  "A Knight's Tale",
  "The Count of Monte Cristo",
  "Robin Hood: Prince of Thieves",
  "The Three Musketeers",
  "Pirates of the Caribbean",
  "The Giver",
  "The Book Thief",
  "Wonder",
  "The Fault in Our Stars",
  "The Perks of Being a Wallflower",
  "Me Before You",
  "Five Feet Apart",
  "Everything, Everything",
  "Love, Simon",
  "Clueless",
  "Mean Girls",
  "Easy A",
  "The DUFF",
  "She's the Man",
  "10 Things I Hate About You",
  "The Princess Switch",
  "A Christmas Prince",
  "The Knight Before Christmas",
  "Jingle Jangle",
  "Klaus",
  "Arthur Christmas",
  "Rise of the Guardians",
  "The Lego Movie",
  "The Lego Batman Movie",
  "Cloudy with a Chance of Meatballs",
  "Hotel Transylvania",
  "Monster House",
  "Coraline",
  "ParaNorman",
  "The Boxtrolls",
  "Kubo and the Two Strings",
  "Missing Link",
  "The Mitchells vs. The Machines",
  "Vivo",
  "The Willoughbys"
];

/**
 * Get a random family-friendly movie title
 * @returns {string} A random movie title
 */
export function getRandomMovieName() {
  const randomIndex = Math.floor(Math.random() * FAMILY_FRIENDLY_MOVIES.length);
  return FAMILY_FRIENDLY_MOVIES[randomIndex];
}

/**
 * Get multiple random movie names (no duplicates)
 * @param {number} count - Number of movie names to get
 * @returns {string[]} Array of random movie titles
 */
export function getRandomMovieNames(count) {
  const shuffled = [...FAMILY_FRIENDLY_MOVIES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, FAMILY_FRIENDLY_MOVIES.length));
}
